
-- Table to track actions taken on AI recommendations
CREATE TABLE IF NOT EXISTS actions_tracking (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    airtable_id TEXT NOT NULL,
    customer_name TEXT,
    action_type TEXT,
    status TEXT DEFAULT 'completed',
    handled_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    node_id TEXT -- Useful for debugging
);

-- Table to track data synchronization history
CREATE TABLE IF NOT EXISTS sync_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sync_time TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    status TEXT NOT NULL, -- 'success' or 'failed'
    details JSONB,
    records_synced INTEGER DEFAULT 0
);

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_actions_airtable_id ON actions_tracking(airtable_id);
CREATE INDEX IF NOT EXISTS idx_sync_time ON sync_history(sync_time DESC);

-- Example seed for sync health (optional, for testing)
-- INSERT INTO sync_history (status, sync_time) VALUES ('success', NOW());
